// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqrszyykyikwckdzaxxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxcnN6eXlreWlrd2NrZHpheHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNTE1NDAsImV4cCI6MjA1MjYyNzU0MH0.ShGvn4Egw4me8oZ9ZB4XzL9L_G5EC6PdJDh6ixq8ZqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);